conf_threshold: 0.5
crop_enabled: true
crop_h: 516
crop_w: 586
crop_x: 300
crop_y: 180
data_collection_enabled: false
data_collection_interval: 1
drowsy_time_threshold: 1.5
eye_closed_threshold: 0.2
eye_img_size: 128
eye_logic_mode: 0
eye_model_path: weights/tiny_attention_eye.onnx
frame_rate: 30
iou_threshold: 0.35
led_pin: 21
server_sync_ip: 10.0.71.27:8002
yolo_img_size: 224
yolo_path: weights/yolo-17-12.onnx
